### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Get green background
- [x] Get picture of car
- [x] Make sure it is facing the right direction
