### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create object with direction property
- [x] Listen for arrow key events
- [x] Rotate as necessary
- [x] Test
