### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to data model
- [x] Position the car absolute
- [x] Figure out how to move the car
- [x] Make sure it moves smoothly
- [x] Add the to eventlistener handling code if user presses space
- [x] Test
