### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by cbrisk** [cbrisk/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add boolean to data model
- [x] Stop car when user presses space again
       - [ ] Use clearInterval for stopping
- [x] Restart car when user presses space once more
- [x] Test
